### PR TITLE
New algorithm for merging overlays and extensions

### PR DESCRIPTION
**Pull request by ddenisenko**
Also support for the loadApiAsync(‘master.raml’,
[‘overlay.raml’,’extension.raml’], options) and loadApi(‘master.raml’,
[‘overlay.raml’,’extension.raml’], options) APIs

Latest parser updates, also renamed loadApi->loadApiSync,
loadApiAsync->loadApi, updated samples, updated web bundle.

### CODE REVIEW

**Comment by rpaterson** [comment]
Can't get it to work :-(  I tried an extension example from the spec:

librarybooks.raml:
```yaml
#%RAML 1.0
# This file is located at librarybooks.raml
title: Book Library API
documentation:
  - title: Introduction
    content: Automated access to books
  - title: Licensing
    content: Please respect copyrights on our books.
/books:
  description: The collection of library books
  get:
```

administrativeExtension.raml:
```yaml
#%RAML 1.0 Extension
usage: Add administrative functionality
masterRef: librarybooks.raml
/books:
  post:
    description: Add a new book to the collection
```

code:
```
var parser = require('../../src/raml1Parser');
var api = parser.loadApi('librarybooks.raml', ['administrativeExtension.raml']);
console.log(JSON.stringify(api.toJSON(), null, 2));
```

output:
```json
{
  "usage": "Add administrative functionality",
  "masterRef": "librarybooks.raml",
  "/books": {
    "post": {
      "description": "Add a new book to the collection"
    }
  }
}
```

The parser doesn't error but when I call .toJSON() on the output it just gives me the extension - not the merged RAML.  Am I doing something wrong?

**Comment by ddenisenko** [comment]
That's because `toJSON` should be banned and erased from existence :)
It works on low-level of AST, and that is not what user actually works with when developing AST-based code.

For debug purpose please use `api.highLevel().printDetails()` returning a string with more detailed AST printout.

If you develop a code that analyses AST, please rely on AST itself.

**Comment by rpaterson** [comment]
Ah ok - I was just copying the existing tests.  Using `api.highLevel().printDetails()` it looks good.  Thank you!  :+1:

**Comment by sichvoge** [comment]
issue: lets assume something like `loadApiAsync('overlay.raml',[''],options)` so an array with an empty string parameter. we should catch that right? currently i am getting the following `{ [Error: EISDIR: illegal operation on a directory, read] errno: -21, code: 'EISDIR', syscall: 'read' }`

**Comment by sichvoge** [comment]
We should also check for null input etc. Currently I am getting that `[TypeError: extensionsAndOverlays.forEach is not a function]` when executing on `loadApiAsync('overlay.raml', null,options)`

**Comment by ddenisenko** [comment]
Fixed the validation.

**Pull request merged**
