### PR TITLE
Add test for modularization

### PR DESCRIPTION
**Pull request by rpaterson**
Examples from RAML 1.0 spec.  (test currently errors)

### CODE REVIEW

**Comment by ddenisenko** [comment]
I am not sure that the merging API will look exactly like in the current JS file, but let it be so for a while, we can always fix the test later.

**Comment by rpaterson** [comment]
Sure I just threw it in as an example.

**Comment by sichvoge** [comment]
@rpaterson, that feature still needs to be implemented. it is definitely on our todo list. when we've done that we will merge the test and see if that still fails.

**Comment by rpaterson** [comment]
Sounds good.

**Comment by rpaterson** [comment]
Refactored for the changes in https://github.com/raml-org/raml-js-parser-2/pull/55.  The test now passes.

**Comment by ddenisenko** [comment]
I would suggest printing something overridden by overlay or extension (I mean, printing in the code, not via printDetails) to display that override actually happened.

**Comment by sichvoge** [comment]
You should not print it out as a test. You should compare the expected result with the actual programmatically using chai or something else.

**Comment by rpaterson** [comment]
@sichvoge clearly this module needs to add some sort of test framework, but I don't want to do that as part of this PR.  I'll just add the print outs for now.

**Comment by rpaterson** [comment]
added some print outs

**Pull request closed without merging**
